apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pydocs-front
  namespace: front
  annotations:
    custom-hostname: "python-docs"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        custom-hostname: "python-docs"
    spec:
      containers:
        - name: docs-app
          image: 361265061473.dkr.ecr.us-east-1.amazonaws.com/saas-front:0.0.11
          imagePullPolicy: Always
          ports:
            - containerPort: 8080