name: Tag release
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  publish:
    if: ${{ contains(github.ref_name, 'RELEASE') }}
    runs-on: ubuntu-latest
    name: Python 3.8
    steps:
      - uses: actions/checkout@v3
      #TODO add a step for running unit tests
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
          architecture: x64
      - run: pip install -r requirements-dev.txt
      - name: Publish to pypi
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: make pip-pypi